### ISSUE TITLE
review proposal

### ISSUE THREAD

**Issue by orbeckst** [ASU-CompMethodsPhysics-PHY494/final-2018-doubularity#2]
I will review the proposal #1 as soon as you commit it.

@ASU-CompMethodsPhysics-PHY494/doubularity Please leave a comment here once the proposal is available. 

Note that the proposal should have the names of *all team members* on it. There should be 2–4 *specific* objectives with measurable outcomes. It should be about 1 page but it can be longer if necessary.

The Proposal should guide your overall directions of the project and form the basis of your decisions of what to work on.

**Comment by orbeckst** [comment]
Please address the following points
1. add all team members to the proposals (author list under the title)
2. The section that you called "Abstract" is "Approach" (and Abstract is a summary): rename to _Approach_
3. add a citation for the Lagrangian of light around a black hole (and add it to a References sections)
4. add links to GitHub repos for raytracers that you might want to use
5. The text on _how_ you are going to address the problem (Verlet etc) should go into _Approach_ – these are not objectives.
6. Number your objectives and be specific.

Minor points
1. use single-line spacing
2. create a PDF of the Word doc and add the PDF to the repo (viewing PDFs is much easier)
3. I would not worry about a graphical user interface but you can add it as a stretch goal (but be specific in what you want to achieve).

Note that the 1-page limit is a soft limit and only a guide line; if you need more space then that's ok.

Once you have addressed the points above, please leave a message on this issue and I will review again.

**Comment by tunaLandslide** [comment]
I made sure to fix these issues as well as I could. There wasn't a specific
source for the Lagrangian, but I put in some working out for the equation

**Comment by orbeckst** [comment]
I approve the Proposal. Please get started on the project.

Btw, you misspelt [Schwarzschild](https://en.wikipedia.org/wiki/Karl_Schwarzschild).
